CASC_PATH = '../lib/haarcascade_frontalface_default.xml'
SIZE_FACE = 48
EMOTIONS = ['angry', 'disgusted', 'fearful', 'happy', 'sad', 'surprised', 'neutral']
DATASET_DIRECTORY='F:\\emotion_recognition\dataset'
SAVE_MODEL_FILENAME = 'results'
SAVE_TRAINING_IMAGES_FILENAME = 'training_set.npy'
SAVE_TRAINING_LABELS_FILENAME = 'training_labels.npy'
SAVE_VALIDATION_IMAGES_FILENAME = 'validation_set.npy'
SAVE_VALIDATION_LABELS_FILENAME = 'validation_labels.npy'
TRAINING_DATA_PERCENTAGE=0.8
TOTAL_DATASET_COUNT=13974